version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=cscart
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:8.0
    container_name: my-laravel-db
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=cscart
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
